version: "2"
services:
  api:
    container_name: workast_api
    build: .
    environment:
        # The mongodb host is the database service name
        DOCKER_MONGODB_URL: mongodb://mongo:27017/workast
        NODE_ENV: '${NODE_ENV}'
        API_TOKEN: '${API_TOKEN}' 
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: workast_mongo
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    expose:
      - 27017
volumes:
  mongodb:
