 /v1/users/{userId}/articles:
    post:
        tags: 
            - articles
        summary: Creates an article
        description: Creates an article 
        operationId: createArticle.js
        consumes:
            - application/json
            - application/x-www-form-urlencoded
        produces:
            - application/json
        parameters:
        -   name: Authorization
            in: header
            description: Authorization token
            required: true
            type: string
            example: Bearer 5CD4ED173E1C95FE763B753A297D5
        -   name: userId
            in: path
            description: user id
            required: true
            type: string
            example: 1
        -   name: body
            in: body
            required: true
            schema:
                type: object
                required:
                    - title
                    - text
                properties:
                    title:
                        type: string
                        example: some title
                    text:
                        type: string
                        example: some text
                    tags:
                        type: array
                        items:
                            type: string
                            example: some tag
        responses:
            201:
                description: Created
                headers:
                    Location:
                        description: http://localhost:8080/api/v1/users/1/articles/1
                        type: string
                        format: uri
                schema:
                    type: object
                    required:
                        - _links
                    properties:
                        _links:
                            type: object
                            required:
                                - self
                            properties:
                                self:
                                    type: object
                                    required:
                                        - href
                                    properties:
                                        href:
                                            type: string
                                            format: uri
                                            example: http://localhost:8080/users/1/articles/1
            400:
                description: Bad Request
            401:
                description: Unauthorized
            500:
                description: Internal server error
