 /v1/users:
    post:
        tags: 
            - users
        summary: Creates a user
        description: Creates a user 
        operationId: createUser.js
        consumes:
            - application/json
            - application/x-www-form-urlencoded
        produces:
            - application/json
        parameters:
        -   name: Authorization
            in: header
            description: Authorization token
            required: true
            type: string
            example: Bearer 5CD4ED173E1C95FE763B753A297D5
        -   name: body
            in: body
            required: true
            schema:
                type: object
                required:
                    - name
                properties:
                    name:
                        type: string
                        example: Carlos
                    avatar:
                        type: string
                        example: http://my_avatar
                        format: uri
        responses:
            201:
                description: Created
                headers:
                    Location:
                        description: http://localhost:8080/api/v1/users/1
                        type: string
                        format: uri
                schema:
                    type: object
                    required:
                        - _links
                    properties:
                        _links:
                            type: object
                            required:
                                - self
                            properties:
                                self:
                                    type: object
                                    required:
                                        - href
                                    properties:
                                        href:
                                            type: string
                                            format: uri
                                            example: http://localhost:8080/api/v1/users/1
                                createArticle:
                                    type: object
                                    required:
                                        - href
                                    properties:
                                        href:
                                            type: string
                                            format: uri
                                            example: http://localhost:8080/api/v1/users/1/articles
                                listArticles:
                                    type: object
                                    required:
                                        - href
                                    properties:
                                        href:
                                            type: string
                                            format: uri
                                            example: http://localhost:8080/api/v1/articles
            400:
                description: Bad Request
            401:
                description: Unauthorized
            500:
                description: Internal server error
